### ISSUE TITLE
[Feature request] Tool calling support

### ISSUE THREAD

**Issue by binarybana** [simonw/llm-mlx#21]
First time user of `llm` with the `mlx` backend. Really amazing UX and workflow you've got working here. Thank you!

I've downloaded several models that I'd expect to support tool calling (eg Qwen3) but it looks like tool calling is not supported with any of them, so I'm assuming it's a [limitation of the plugin](https://llm.datasette.io/en/stable/plugins/plugin-hooks.html#plugin-hooks-register-tools) to expose it?

```
❯ llm models --options
...
MlxModel: mlx-community/Mistral-Small-24B-Instruct-2501-4bit (aliases: ms)
  Options:
    max_tokens: int
    unlimited: boolean
    temperature: float
    top_p: float
    min_p: float
    min_tokens_to_keep: int
    seed: int
  Features:
  - streaming
MlxModel: mlx-community/Qwen3-30B-A3B-4bit-DWQ-053125 (aliases: moe)
  Options:
    max_tokens: int
    unlimited: boolean
    temperature: float
    top_p: float
    min_p: float
    min_tokens_to_keep: int
    seed: int
  Features:
  - streaming
MlxModel: mlx-community/Qwen3-1.7B-4bit (aliases: smol)
  Options:
    max_tokens: int
    unlimited: boolean
    temperature: float
    top_p: float
    min_p: float
    min_tokens_to_keep: int
    seed: int
  Features:
  - streaming
```
Expected to see: `tools` in Features list above.
